
blueprint:
  name: GWM Selected Vehicle Tracker
  description: Updates the `device_tracker.gwmbrasil_selected_vehicle` entity with the location of the vehicle selected in the `select.gwmbrasil_veiculos_registrados` dropdown.
  domain: automation
  source_url: https://github.com/havaleiros/hassio-haval-h6-to-mqtt/blob/main/haval-h6-mqtt/files/automation_blueprint.yaml
  input: {}

trigger:
  - platform: state
    entity_id: select.gwmbrasil_veiculos_registrados

action:
  - service: mqtt.publish
    data:
      topic: "homeassistant/device_tracker/gwmbrasil_selected_vehicle/attributes"
      payload_template: >
        {% set vehicle_tracker = 'device_tracker.gwmbrasil_' + trigger.to_state.state.lower() %}
        {% set lat = state_attr(vehicle_tracker, 'latitude') %}
        {% set lon = state_attr(vehicle_tracker, 'longitude') %}
        {% set acc = state_attr(vehicle_tracker, 'gps_accuracy') %}
        {% set imsi = state_attr(vehicle_tracker, 'imsi') %}
        {% set icon = state_attr(vehicle_tracker, 'icon') %}
        {
          "latitude": {{ lat }},
          "longitude": {{ lon }},
          "gps_accuracy": {{ acc }},
          "imsi": "{{ imsi }}",
          "icon": "{{ icon }}"
        }
